services:
  postgres:
    image: postgres:16
    container_name: eatctrl_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eatctrl
    ports:
      - "5432:5432"
    volumes:
      - eatctrl_pg:/var/lib/postgresql/data

volumes:
  eatctrl_pg:
